-- CREATE TABLE `VISITOR` (
-- 	`VISITOR_ID`	VARCHAR(255)	NOT NULL,
-- 	`NOTICE_ID`	VARCHAR(255)	NOT NULL,
-- 	`VISITOR_NAME`	VARCHAR(255)	NULL
-- );

INSERT INTO VISITOR
(VISITOR_ID, NOTICE_ID, VISITOR_NAME)
VALUES
('VISITE_01', 'NOTICE_01', '홍길동');

INSERT INTO VISITOR
(VISITOR_ID, NOTICE_ID, VISITOR_NAME)
VALUES
('VISITE_09', 'NOTICE_04', '임현서');