-- CREATE TABLE `NOTICE` (
-- 	`NOTICE_ID`	VARCHAR(255)	NOT NULL,
-- 	`CONTENTS`	VARCHAR(255)	NULL,
-- 	`WRITER`	VARCHAR(255)	NULL
-- );

INSERT INTO NOTICE
(NOTICE_ID, CONTENTS, WRITER)
VALUES
('NOTICE_01', '서비스 점검 안내', '관리자');