INSERT INTO NOTICE
(NOTICE_ID, CONTENTS, WRITER)
VALUES
('NOTICE_05', '서비스 이용약관 변경 안내', '운영팀');


INSERT INTO VISITOR
(VISITOR_ID, NOTICE_ID, VISITOR_NAME)
VALUES
('VISITE_10', 'NOTICE_05', '강수민'),
('VISITE_11', 'NOTICE_05', '백지영'),
('VISITE_12', 'NOTICE_05', '박정희');

SELECT *
FROM NOTICE;

SELECT *
FROM VISITOR;