CREATE TABLE `BOARDS` (
	`BOARDS_ID`	VARCHAR(255)	NOT NULL,
	`TOPIC`	VARCHAR(255)	NULL,
	`NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `COMMENT` (
	`COMMENT_ID`	VARCHAR(255)	NOT NULL,
	`BOARDS_ID`	VARCHAR(255)	NOT NULL,
	`COMMENTS`	VARCHAR(255)	NULL
);

ALTER TABLE `BOARDS` ADD CONSTRAINT `PK_BOARDS` PRIMARY KEY (
	`BOARDS_ID`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (
	`COMMENT_ID`,
	`BOARDS_ID`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `FK_BOARDS_TO_COMMENT_1` FOREIGN KEY (
	`BOARDS_ID`
)
REFERENCES `BOARDS` (
	`BOARDS_ID`
);

