CREATE TABLE `HOBBY` (
	`HOBBY_ID`	VARCHAR(50)	NOT NULL,
	`HOBBY`	VARCHAR(255)	NULL
);

CREATE TABLE `USERS_DATA` (
	`USERS_DATA_ID`	VARCHAR(50)	NOT NULL,
	`SEX_ID`	VARCHAR(50)	NOT NULL,
	`NAME`	VARCHAR(255)	NULL,
	`AGE`	VARCHAR(255)	NULL,
	`PHONE_NUMBER`	VARCHAR(255)	NULL,
	`EMAIL`	VARCHAR(255)	NULL
);

CREATE TABLE `SEX` (
	`SEX_ID`	VARCHAR(50)	NOT NULL,
	`SEX`	VARCHAR(255)	NULL
);

CREATE TABLE `ADDRESS` (
	`ADDRESS_ID`	VARCHAR(50)	NOT NULL,
	`ADDRESS`	VARCHAR(255)	NULL
);

CREATE TABLE `USERS_INFORMATION` (
	`USERS_INFORMATION_ID`	VARCHAR(50)	NOT NULL,
	`USERS_DATA_ID`	VARCHAR(50)	NOT NULL,
	`HOBBY_ID`	VARCHAR(50)	NOT NULL,
	`ADDRESS_ID`	VARCHAR(50)	NOT NULL
);

ALTER TABLE `HOBBY` ADD CONSTRAINT `PK_HOBBY` PRIMARY KEY (
	`HOBBY_ID`
);

ALTER TABLE `USERS_DATA` ADD CONSTRAINT `PK_USERS_DATA` PRIMARY KEY (
	`USERS_DATA_ID`,
	`SEX_ID`
);

ALTER TABLE `SEX` ADD CONSTRAINT `PK_SEX` PRIMARY KEY (
	`SEX_ID`
);

ALTER TABLE `ADDRESS` ADD CONSTRAINT `PK_ADDRESS` PRIMARY KEY (
	`ADDRESS_ID`
);

ALTER TABLE `USERS_INFORMATION` ADD CONSTRAINT `PK_USERS_INFORMATION` PRIMARY KEY (
	`USERS_INFORMATION_ID`,
	`USERS_DATA_ID`,
	`HOBBY_ID`,
	`ADDRESS_ID`
);

ALTER TABLE `USERS_DATA` ADD CONSTRAINT `FK_SEX_TO_USERS_DATA_1` FOREIGN KEY (
	`SEX_ID`
)
REFERENCES `SEX` (
	`SEX_ID`
);

ALTER TABLE `USERS_INFORMATION` ADD CONSTRAINT `FK_USERS_DATA_TO_USERS_INFORMATION_1` FOREIGN KEY (
	`USERS_DATA_ID`
)
REFERENCES `USERS_DATA` (
	`USERS_DATA_ID`
);

ALTER TABLE `USERS_INFORMATION` ADD CONSTRAINT `FK_HOBBY_TO_USERS_INFORMATION_1` FOREIGN KEY (
	`HOBBY_ID`
)
REFERENCES `HOBBY` (
	`HOBBY_ID`
);

ALTER TABLE `USERS_INFORMATION` ADD CONSTRAINT `FK_ADDRESS_TO_USERS_INFORMATION_1` FOREIGN KEY (
	`ADDRESS_ID`
)
REFERENCES `ADDRESS` (
	`ADDRESS_ID`
);

