CREATE TABLE `CARS_NAME` (
	`CARS_NAME_ID`	VARCHAR(255)	NOT NULL,
	`CARS_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `COMPANY_NAME` (
	`COMPANY_ID`	VARCHAR(255)	NOT NULL,
	`COMPANY_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `YEAR` (
	`YEAR_ID`	VARCHAR(255)	NOT NULL,
	`CAR_YEAR`	VARCHAR(255)	NULL
);

CREATE TABLE `OPTIONS` (
	`OPTION_ID`	VARCHAR(255)	NOT NULL,
	`NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `CARS_INFORMATION` (
	`CARS_INFORMATION_ID`	TEXT(65535)	NOT NULL,
	`OPTION_ID`	VARCHAR(255)	NOT NULL,
	`COMPANY_ID`	VARCHAR(255)	NOT NULL,
	`CARS_NAME_ID`	VARCHAR(255)	NOT NULL,
	`YEAR_ID`	VARCHAR(255)	NOT NULL
);

ALTER TABLE `CARS_NAME` ADD CONSTRAINT `PK_CARS_NAME` PRIMARY KEY (
	`CARS_NAME_ID`
);

ALTER TABLE `COMPANY_NAME` ADD CONSTRAINT `PK_COMPANY_NAME` PRIMARY KEY (
	`COMPANY_ID`
);

ALTER TABLE `YEAR` ADD CONSTRAINT `PK_YEAR` PRIMARY KEY (
	`YEAR_ID`
);

ALTER TABLE `OPTIONS` ADD CONSTRAINT `PK_OPTIONS` PRIMARY KEY (
	`OPTION_ID`
);

ALTER TABLE `CARS_INFORMATION` ADD CONSTRAINT `PK_CARS_INFORMATION` PRIMARY KEY (
	`CARS_INFORMATION_ID`,
	`OPTION_ID`,
	`COMPANY_ID`,
	`CARS_NAME_ID`,
	`YEAR_ID`
);

ALTER TABLE `CARS_INFORMATION` ADD CONSTRAINT `FK_OPTIONS_TO_CARS_INFORMATION_1` FOREIGN KEY (
	`OPTION_ID`
)
REFERENCES `OPTIONS` (
	`OPTION_ID`
);

ALTER TABLE `CARS_INFORMATION` ADD CONSTRAINT `FK_COMPANY_NAME_TO_CARS_INFORMATION_1` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `COMPANY_NAME` (
	`COMPANY_ID`
);

ALTER TABLE `CARS_INFORMATION` ADD CONSTRAINT `FK_CARS_NAME_TO_CARS_INFORMATION_1` FOREIGN KEY (
	`CARS_NAME_ID`
)
REFERENCES `CARS_NAME` (
	`CARS_NAME_ID`
);

ALTER TABLE `CARS_INFORMATION` ADD CONSTRAINT `FK_YEAR_TO_CARS_INFORMATION_1` FOREIGN KEY (
	`YEAR_ID`
)
REFERENCES `YEAR` (
	`YEAR_ID`
);

